export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

export const PRODUCT_SCREEN_REQUEST = "PRODUCT_SCREEN_REQUEST";
export const PRODUCT_SCREEN_SUCCESS = "PRODUCT_SCREEN_SUCCESS";
export const PRODUCT_SCREEN_FAIL = "PRODUCT_SCREEN_FAIL";

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";

export const SIGNIN_USER_REQUEST = "SIGNIN_USER_REQUEST";
export const SIGNIN_USER_SUCCESS = "SIGNIN_USER_SUCCESS";
export const SIGNIN_USER_FAIL = "SIGNIN_USER_FAIL";
export const SIGNOUT_USER = "SIGNOUT_USER";

export const SHIPPING_INFO = "SHIPPING_INFO";

export const ADD_TO_BUY = "ADD_TO_BUY";

export const SAVE_SHIPPING = "SAVE_SHIPPING";
