export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

export const PRODUCT_SCREEN_REQUEST = "PRODUCT_SCREEN_REQUEST";
export const PRODUCT_SCREEN_SUCCESS = "PRODUCT_SCREEN_SUCCESS";
export const PRODUCT_SCREEN_FAIL = "PRODUCT_SCREEN_FAIL";
