const data = {
  bags: [
    {
      _id: 1,
      productname: "Blue Sheet Premium Bag",
      price: 4000,
      path: "/bags/bluesheet.jpg",
      countinstock: 5,
      category: "Bags",
    },
    {
      _id: 2,
      productname: "Grey Sheet Premium Bag",
      price: 6000,
      path: "/bags/greysheet.jpg",
      countinstock: 5,
      category: "Bags",
    },
    {
      _id: 3,
      productname: "Orange Sheet Premium Bag",
      price: 7000,
      path: "/bags/orangesheet.jpg",
      countinstock: 5,
      category: "Bags",
    },
    {
      _id: 4,
      productname: "RedSheet Sheet Premium Bag",
      price: 3000,
      path: "/bags/redsheet.jpg",
      countinstock: 5,
      category: "Bags",
    },
    {
      _id: 5,
      productname: "Sultani Sheet Premium Bag",
      price: 5000,
      path: "/bags/sultanibag.jpg",
      countinstock: 5,
      category: "Bags",
    },
    {
      _id: 6,
      productname: "Tigerlayer Premium Bag",
      price: 4000,
      path: "/bags/tigerlayer.jpg",
      countinstock: 5,
      category: "Bags",
    },
  ],
  laptops: [
    {
      _id: 7,
      productname: "Acer Predator",
      price: 150000,
      path: "/laptops/acerpredator.jpg",
      countinstock: 5,
      category: "Computer",
    },
    {
      _id: 8,
      productname: "Acer Spin Gaming Laptop",
      price: 100000,
      path: "/laptops/acerspin.jpg",
      countinstock: 5,
      category: "Computer",
    },
    {
      _id: 9,
      productname: "Asus Rog Gaming Laptop",
      price: 130000,
      path: "/laptops/asusrog.jpg",
      countinstock: 5,
      category: "Computer",
    },
    {
      _id: 10,
      productname: "Asus Tuff Gaming Laptop",
      price: 100000,
      path: "/laptops/asustuf.jpg",
      countinstock: 5,
      category: "Computer",
    },
    {
      _id: 11,
      productname: "Dell AlienWare gaming Laptop",
      price: 150000,
      path: "/laptops/dellalienware.jpg",
      countinstock: 5,
      category: "Computer",
    },
    {
      _id: 12,
      productname: "Hp Envy Laptop",
      price: 80000,
      path: "/laptops/hpenvy.jpg",
      countinstock: 5,
      category: "Computer",
    },
  ],
  mobiles: [
    {
      _id: 13,
      productname: "MI 10",
      price: 40000,
      path: "/mobiles/mi10.jpg",
      countinstock: 5,
      category: "Mobiles",
    },
    {
      _id: 14,
      productname: "Poco Premium Mobile",
      price: 32000,
      path: "/mobiles/poco.jpg",
      countinstock: 5,
      category: "Mobiles",
    },
    {
      _id: 15,
      productname: "Redmi Note 9",
      price: 30000,
      path: "/mobiles/redmi.jpg",
      countinstock: 5,
      category: "Mobiles",
    },
    {
      _id: 16,
      productname: "Redmi Prime ",
      price: 30000,
      path: "/mobiles/redmiprime.jpg",
      countinstock: 5,
      category: "Mobiles",
    },
    {
      _id: 17,
      productname: "Samsung S12",
      price: 50000,
      path: "/mobiles/samsung.jpg",
      countinstock: 5,
      category: "Mobiles",
    },
    {
      _id: 18,
      productname: "Vivo V1",
      price: 50000,
      path: "/mobiles/vivo.jpg",
      countinstock: 5,
      category: "Mobiles",
    },
  ],
  clothes: [
    {
      _id: 19,
      productname: "Casual Wear For Men",
      price: 4000,
      path: "/fashion/casual.jpg",
      countinstock: 5,
      category: "Wearing",
    },
    {
      _id: 20,
      productname: "Couples Duo Wear",
      price: 2000,
      path: "/fashion/couple.jpg",
      countinstock: 5,
      category: "Wearing",
    },
    {
      _id: 21,
      productname: "Formal Dress For Men",
      price: 3000,
      path: "/fashion/formalmen.jpg",
      countinstock: 5,
      category: "Wearing",
    },
    {
      _id: 22,
      productname: "Stylish Formal Dress For Men",
      price: 3000,
      path: "/fashion/formalmen2.jpg",
      countinstock: 5,
      category: "Wearing",
    },
    {
      _id: 23,
      productname: "Shirt For Women",
      price: 2000,
      path: "/fashion/shirtwomen.jpg",
      countinstock: 5,
      category: "Wearing",
    },
    {
      _id: 24,
      productname: "Shirt and Jeans Combo For Women",
      price: 2000,
      path: "/fashion/topjeans.jpg",
      countinstock: 5,
      category: "Wearing",
    },
  ],
};
export default data;
